# Generated by YCM Generator at 2017-05-11 23:08:45.391698

# This file is NOT licensed under the GPLv3, which is the license for the rest
# of YouCompleteMe.
#
# Here's the license text for this file:
#
# This is free and unencumbered software released into the public domain.
#
# Anyone is free to copy, modify, publish, use, compile, sell, or
# distribute this software, either in source code form or as a compiled
# binary, for any purpose, commercial or non-commercial, and by any
# means.
#
# In jurisdictions that recognize copyright laws, the author or authors
# of this software dedicate any and all copyright interest in the
# software to the public domain. We make this dedication for the benefit
# of the public at large and to the detriment of our heirs and
# successors. We intend this dedication to be an overt act of
# relinquishment in perpetuity of all present and future rights to this
# software under copyright law.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
# MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
# IN NO EVENT SHALL THE AUTHORS BE LIABLE FOR ANY CLAIM, DAMAGES OR
# OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
# ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
# OTHER DEALINGS IN THE SOFTWARE.
#
# For more information, please refer to <http://unlicense.org/>

import os
import ycm_core

flags = [
    '-x',
    'c++',
    '-DBUILD_DATE="2017-05-11 23:08:44"',
    '-DBUILD_DIR="/home/mesos/mesos-git/mesos/build/3rdparty/libprocess"',
    '-DBUILD_FLAGS=""',
    '-DBUILD_GIT_BRANCH="refs/heads/master"',
    '-DBUILD_GIT_SHA="d2afca0b78842f07d84c893815bf4b811c8c2f3f"',
    '-DBUILD_JAVA_JVM_LIBRARY="/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/amd64/server/libjvm.so"',
    '-DBUILD_TIME="1494524324"',
    '-DBUILD_USER=""',
    '-DHAS_AUTHENTICATION=1',
    '-DHAVE_APR_POOLS_H=1',
    '-DHAVE_CXX11=1',
    '-DHAVE_DLFCN_H=1',
    '-DHAVE_FTS_H=1',
    '-DHAVE_INTTYPES_H=1',
    '-DHAVE_LIBAPR_1=1',
    '-DHAVE_LIBCURL=1',
    '-DHAVE_LIBSASL2=1',
    '-DHAVE_LIBSVN_DELTA_1=1',
    '-DHAVE_LIBSVN_SUBR_1=1',
    '-DHAVE_LIBZ=1',
    '-DHAVE_MEMORY_H=1',
    '-DHAVE_PTHREAD=1',
    '-DHAVE_PTHREAD_PRIO_INHERIT=1',
    '-DHAVE_PYTHON="2.7"',
    '-DHAVE_STDINT_H=1',
    '-DHAVE_STDLIB_H=1',
    '-DHAVE_STRINGS_H=1',
    '-DHAVE_STRING_H=1',
    '-DHAVE_SVN_DELTA_H=1',
    '-DHAVE_SVN_VERSION_H=1',
    '-DHAVE_SYS_STAT_H=1',
    '-DHAVE_SYS_TYPES_H=1',
    '-DHAVE_UNISTD_H=1',
    '-DLEVELDB_ATOMIC_PRESENT',
    '-DLEVELDB_PLATFORM_POSIX',
    '-DLIBDIR="/usr/local/lib"',
    '-DLT_OBJDIR=".libs/"',
    '-DMESOS_HAS_JAVA=1',
    '-DMESOS_HAS_PYTHON=1',
    '-DOS_LINUX',
    '-DPACKAGE="mesos"',
    '-DPACKAGE_BUGREPORT=""',
    '-DPACKAGE_NAME="mesos"',
    '-DPACKAGE_STRING="mesos 1.4.0"',
    '-DPACKAGE_TARNAME="mesos"',
    '-DPACKAGE_URL=""',
    '-DPACKAGE_VERSION="1.4.0"',
    '-DPIC',
    '-DPICOJSON_USE_INT64',
    '-DPKGDATADIR="/usr/local/share/mesos"',
    '-DPKGLIBEXECDIR="/usr/local/libexec/mesos"',
    '-DPKGMODULEDIR="/usr/local/lib/mesos/modules"',
    '-DSTDC_HEADERS=1',
    '-DVERSION="1.4.0"',
    '-D__STDC_FORMAT_MACROS',
    '-I.',
    '-I../../../3rdparty/libprocess',
    '-I../../../3rdparty/libprocess/../stout/include',
    '-I../../../3rdparty/libprocess/include',
    '-I../../3rdparty',
    '-I../../3rdparty/libprocess/include',
    '-I../../3rdparty/stout/include',
    '-I../../include',
    '-I../../src',
    '-I../3rdparty/elfio-3.2',
    '-I../3rdparty/glog-0.3.3/src',
    '-I../3rdparty/leveldb-1.19/include',
    '-I../3rdparty/nvml-352.79',
    '-I../3rdparty/picojson-1.3.0',
    '-I../3rdparty/protobuf-2.6.1/src',
    '-I../3rdparty/zookeeper-3.4.8/src/c/generated',
    '-I../3rdparty/zookeeper-3.4.8/src/c/include',
    '-I../elfio-3.2',
    '-I../glog-0.3.3/src',
    '-I../http-parser-2.6.2',
    '-I../include',
    '-I../include/mesos',
    '-I../libev-4.22',
    '-I../picojson-1.3.0',
    '-I./include',
    '-I/usr/include/apr-1',
    '-I/usr/include/apr-1.0',
    '-I/usr/include/subversion-1',
    '-Igmock-1.7.0',
    '-Igmock-1.7.0/gtest',
    '-Igmock-1.7.0/gtest/include',
    '-Igmock-1.7.0/gtest/src',
    '-Igmock-1.7.0/include',
    '-Igmock-1.7.0/src',
    '-Wall',
    '-Werror',
    '-Wformat-security',
    '-Wno-unused-local-typedefs',
    '-Wsign-compare',
    '-std=c++0x',
    '-std=c++11',
    '-isystem', '../3rdparty/boost-1.53.0',
    '-isystem', '../boost-1.53.0',
]


# Set this to the absolute path to the folder (NOT the file!) containing the
# compile_commands.json file to use that instead of 'flags'. See here for
# more details: http://clang.llvm.org/docs/JSONCompilationDatabase.html
#
# You can get CMake to generate this file for you by adding:
#   set( CMAKE_EXPORT_COMPILE_COMMANDS 1 )
# to your CMakeLists.txt file.
#
# Most projects will NOT need to set this to anything; you can just change the
# 'flags' list of compilation flags. Notice that YCM itself uses that approach.
compilation_database_folder = '/home/mesos/mesos-git/mesos/build'

if os.path.exists( compilation_database_folder ):
  database = ycm_core.CompilationDatabase( compilation_database_folder )
else:
  database = None

SOURCE_EXTENSIONS = [ '.C', '.cpp', '.cxx', '.cc', '.c', '.m', '.mm' ]

def DirectoryOfThisScript():
  return os.path.dirname( os.path.abspath( __file__ ) )


def MakeRelativePathsInFlagsAbsolute( flags, working_directory ):
  if not working_directory:
    return list( flags )
  new_flags = []
  make_next_absolute = False
  path_flags = [ '-isystem', '-I', '-iquote', '--sysroot=' ]
  for flag in flags:
    new_flag = flag

    if make_next_absolute:
      make_next_absolute = False
      if not flag.startswith( '/' ):
        new_flag = os.path.join( working_directory, flag )

    for path_flag in path_flags:
      if flag == path_flag:
        make_next_absolute = True
        break

      if flag.startswith( path_flag ):
        path = flag[ len( path_flag ): ]
        new_flag = path_flag + os.path.join( working_directory, path )
        break

    if new_flag:
      new_flags.append( new_flag )
  return new_flags


def IsHeaderFile( filename ):
  extension = os.path.splitext( filename )[ 1 ]
  return extension in [ '.H', '.h', '.hxx', '.hpp', '.hh' ]


def GetCompilationInfoForFile( filename ):
  # The compilation_commands.json file generated by CMake does not have entries
  # for header files. So we do our best by asking the db for flags for a
  # corresponding source file, if any. If one exists, the flags for that file
  # should be good enough.
  if IsHeaderFile( filename ):
    basename = os.path.splitext( filename )[ 0 ]
    for extension in SOURCE_EXTENSIONS:
      replacement_file = basename + extension
      if os.path.exists( replacement_file ):
        compilation_info = database.GetCompilationInfoForFile(
          replacement_file )
        if compilation_info.compiler_flags_:
          return compilation_info
    return None
  return database.GetCompilationInfoForFile( filename )


def FlagsForFile( filename, **kwargs ):
  if database:
    # Bear in mind that compilation_info.compiler_flags_ does NOT return a
    # python list, but a "list-like" StringVec object
    compilation_info = GetCompilationInfoForFile( filename )
    if not compilation_info:
      return None

    final_flags = MakeRelativePathsInFlagsAbsolute(
      compilation_info.compiler_flags_,
      compilation_info.compiler_working_dir_ )

  else:
    relative_to = DirectoryOfThisScript()
    final_flags = MakeRelativePathsInFlagsAbsolute( flags, relative_to )

  return {
    'flags': final_flags,
    'do_cache': True
  }
